# -*- coding: utf-8 -*-
"""HousePricePredictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o4lXJElZdBbhfd2eor83vHovnblH8Zp-
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn.datasets
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn import metrics

data=sklearn.datasets.fetch_california_housing()

print(data)

df=pd.DataFrame(data.data,columns=data.feature_names)

df.head()

df['price']=data.target

df.head()

X=df.drop(['price'],axis=1)

Y=df['price']

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

model=XGBRegressor()

model.fit(X_train,Y_train)

prediction=model.predict(X_test)

score=metrics.r2_score(Y_test,prediction)

print(score)